//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Client.ConcurrentRequest.PerSessionWithReentrantMode {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PerSessionWithReentrantMode.IPerSessionWithReentrantMode")]
    public interface IPerSessionWithReentrantMode {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerSessionWithReentrantMode/Get", ReplyAction="http://tempuri.org/IPerSessionWithReentrantMode/GetResponse")]
        string Get(string client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerSessionWithReentrantMode/Get", ReplyAction="http://tempuri.org/IPerSessionWithReentrantMode/GetResponse")]
        System.Threading.Tasks.Task<string> GetAsync(string client);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPerSessionWithReentrantModeChannel : WCF.Client.ConcurrentRequest.PerSessionWithReentrantMode.IPerSessionWithReentrantMode, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PerSessionWithReentrantModeClient : System.ServiceModel.ClientBase<WCF.Client.ConcurrentRequest.PerSessionWithReentrantMode.IPerSessionWithReentrantMode>, WCF.Client.ConcurrentRequest.PerSessionWithReentrantMode.IPerSessionWithReentrantMode {
        
        public PerSessionWithReentrantModeClient() {
        }
        
        public PerSessionWithReentrantModeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PerSessionWithReentrantModeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PerSessionWithReentrantModeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PerSessionWithReentrantModeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Get(string client) {
            return base.Channel.Get(client);
        }
        
        public System.Threading.Tasks.Task<string> GetAsync(string client) {
            return base.Channel.GetAsync(client);
        }
    }
}
