//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Client.ConcurrentRequest.SingleInstanceWithSingleMode {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SingleInstanceWithSingleMode.ISingleInstanceWithSingleMode")]
    public interface ISingleInstanceWithSingleMode {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingleInstanceWithSingleMode/Get", ReplyAction="http://tempuri.org/ISingleInstanceWithSingleMode/GetResponse")]
        string Get(string client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingleInstanceWithSingleMode/Get", ReplyAction="http://tempuri.org/ISingleInstanceWithSingleMode/GetResponse")]
        System.Threading.Tasks.Task<string> GetAsync(string client);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISingleInstanceWithSingleModeChannel : WCF.Client.ConcurrentRequest.SingleInstanceWithSingleMode.ISingleInstanceWithSingleMode, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SingleInstanceWithSingleModeClient : System.ServiceModel.ClientBase<WCF.Client.ConcurrentRequest.SingleInstanceWithSingleMode.ISingleInstanceWithSingleMode>, WCF.Client.ConcurrentRequest.SingleInstanceWithSingleMode.ISingleInstanceWithSingleMode {
        
        public SingleInstanceWithSingleModeClient() {
        }
        
        public SingleInstanceWithSingleModeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SingleInstanceWithSingleModeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SingleInstanceWithSingleModeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SingleInstanceWithSingleModeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Get(string client) {
            return base.Channel.Get(client);
        }
        
        public System.Threading.Tasks.Task<string> GetAsync(string client) {
            return base.Channel.GetAsync(client);
        }
    }
}
