//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Client.ConcurrentRequest.SingleInstanceWithConcurrentMode {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SingleInstanceWithConcurrentMode.ISingleInstanceWithConcurrentMode")]
    public interface ISingleInstanceWithConcurrentMode {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingleInstanceWithConcurrentMode/Get", ReplyAction="http://tempuri.org/ISingleInstanceWithConcurrentMode/GetResponse")]
        string Get(string client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingleInstanceWithConcurrentMode/Get", ReplyAction="http://tempuri.org/ISingleInstanceWithConcurrentMode/GetResponse")]
        System.Threading.Tasks.Task<string> GetAsync(string client);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISingleInstanceWithConcurrentModeChannel : WCF.Client.ConcurrentRequest.SingleInstanceWithConcurrentMode.ISingleInstanceWithConcurrentMode, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SingleInstanceWithConcurrentModeClient : System.ServiceModel.ClientBase<WCF.Client.ConcurrentRequest.SingleInstanceWithConcurrentMode.ISingleInstanceWithConcurrentMode>, WCF.Client.ConcurrentRequest.SingleInstanceWithConcurrentMode.ISingleInstanceWithConcurrentMode {
        
        public SingleInstanceWithConcurrentModeClient() {
        }
        
        public SingleInstanceWithConcurrentModeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SingleInstanceWithConcurrentModeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SingleInstanceWithConcurrentModeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SingleInstanceWithConcurrentModeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Get(string client) {
            return base.Channel.Get(client);
        }
        
        public System.Threading.Tasks.Task<string> GetAsync(string client) {
            return base.Channel.GetAsync(client);
        }
    }
}
