//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Client.ConcurrentRequest.PerSessionWithSingleMode {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PerSessionWithSingleMode.IPerSessionWithSingleMode")]
    public interface IPerSessionWithSingleMode {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerSessionWithSingleMode/Get", ReplyAction="http://tempuri.org/IPerSessionWithSingleMode/GetResponse")]
        string Get(string client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerSessionWithSingleMode/Get", ReplyAction="http://tempuri.org/IPerSessionWithSingleMode/GetResponse")]
        System.Threading.Tasks.Task<string> GetAsync(string client);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPerSessionWithSingleModeChannel : WCF.Client.ConcurrentRequest.PerSessionWithSingleMode.IPerSessionWithSingleMode, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PerSessionWithSingleModeClient : System.ServiceModel.ClientBase<WCF.Client.ConcurrentRequest.PerSessionWithSingleMode.IPerSessionWithSingleMode>, WCF.Client.ConcurrentRequest.PerSessionWithSingleMode.IPerSessionWithSingleMode {
        
        public PerSessionWithSingleModeClient() {
        }
        
        public PerSessionWithSingleModeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PerSessionWithSingleModeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PerSessionWithSingleModeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PerSessionWithSingleModeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Get(string client) {
            return base.Channel.Get(client);
        }
        
        public System.Threading.Tasks.Task<string> GetAsync(string client) {
            return base.Channel.GetAsync(client);
        }
    }
}
