//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Client.ConcurrentRequest.PerSessionWithConcurrentMode {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PerSessionWithConcurrentMode.IPerSessionWithConcurrentMode")]
    public interface IPerSessionWithConcurrentMode {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerSessionWithConcurrentMode/Get", ReplyAction="http://tempuri.org/IPerSessionWithConcurrentMode/GetResponse")]
        string Get(string client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerSessionWithConcurrentMode/Get", ReplyAction="http://tempuri.org/IPerSessionWithConcurrentMode/GetResponse")]
        System.Threading.Tasks.Task<string> GetAsync(string client);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPerSessionWithConcurrentModeChannel : WCF.Client.ConcurrentRequest.PerSessionWithConcurrentMode.IPerSessionWithConcurrentMode, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PerSessionWithConcurrentModeClient : System.ServiceModel.ClientBase<WCF.Client.ConcurrentRequest.PerSessionWithConcurrentMode.IPerSessionWithConcurrentMode>, WCF.Client.ConcurrentRequest.PerSessionWithConcurrentMode.IPerSessionWithConcurrentMode {
        
        public PerSessionWithConcurrentModeClient() {
        }
        
        public PerSessionWithConcurrentModeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PerSessionWithConcurrentModeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PerSessionWithConcurrentModeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PerSessionWithConcurrentModeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Get(string client) {
            return base.Channel.Get(client);
        }
        
        public System.Threading.Tasks.Task<string> GetAsync(string client) {
            return base.Channel.GetAsync(client);
        }
    }
}
