//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Client.ConcurrentRequest.PerCallWithConcurrentMode {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PerCallWithConcurrentMode.IPerCallWithConcurrentMode")]
    public interface IPerCallWithConcurrentMode {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPerCallWithConcurrentMode/Get")]
        void Get(string client);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPerCallWithConcurrentMode/Get")]
        System.Threading.Tasks.Task GetAsync(string client);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPerCallWithConcurrentModeChannel : WCF.Client.ConcurrentRequest.PerCallWithConcurrentMode.IPerCallWithConcurrentMode, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PerCallWithConcurrentModeClient : System.ServiceModel.ClientBase<WCF.Client.ConcurrentRequest.PerCallWithConcurrentMode.IPerCallWithConcurrentMode>, WCF.Client.ConcurrentRequest.PerCallWithConcurrentMode.IPerCallWithConcurrentMode {
        
        public PerCallWithConcurrentModeClient() {
        }
        
        public PerCallWithConcurrentModeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PerCallWithConcurrentModeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PerCallWithConcurrentModeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PerCallWithConcurrentModeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Get(string client) {
            base.Channel.Get(client);
        }
        
        public System.Threading.Tasks.Task GetAsync(string client) {
            return base.Channel.GetAsync(client);
        }
    }
}
